name: Web Automation Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write 
  pages: write
  id-token: write

jobs:
  automation-JUnit:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Setup Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Install Chrome and ChromeDriver (jika diperlukan untuk testing UI)
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.3
        with:
          chrome-version: stable

      # Setup Maven and run tests
      - name: Build with Maven
        run: mvn clean install
      
      # Run Tests using Maven (bisa digabung dengan build, tapi dipisah jika ingin eksplisit)
      - name: Run Tests
        run: mvn test
      
      # Archive test results (pastikan sesuai struktur Maven)
      - name: Archive test results
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: TestNG Reports
          path: target/surefire-reports  # lokasi default hasil test TestNG/JUnit di Maven
      
      # Archive test results (pastikan folder ini sesuai output test Anda)
      - name: Archive test results
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: Cucumber Reports
          path: build/reports

      - name: Upload Test Report
        uses: actions/upload-artifact@v4.3.1
        if: always()
        with:
          name: web-test-report
          path: build/reports/tests/test


      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/reports
